const quotes = [
    "Passados 10 minutos da hora, mais ninguém entra!",
    "Isto vai doer, mas eu estou aqui para que doa menos.",
    "Estou a ver que trouxe a capa preservativa ... (tira o trabalho da mica), deixe estar que eu gosto mais ao natural.",
    "Você está aí impávida e serena, que nem freira do Convento de Arouca.",
    "Estou farto disto. Um tipo agora quer é ver mulheres nuas.",
    "Aising? Ising! Em Roma, sê Romano.",
    "Sino? Você não deve gostar mesmo da sua mãe. Então você não sabe que isso é Senosoidal?",
    "Quem não usa a Técnica do Apagador, não é boa pessoa.",
    "A Técnica do Apagador permite-nos reflectir sobre reflecções feitas anteriormente.",
    "É Lagrangeano, não é Lagrangiano. O tipo chamava-se Lagrange e não Lagrangi.",
    "O Professor é como um Pai e às vezes, uma Mãe.",
    "As tipas andam de relationship em relashionship. Aquilo é falta de Pai.",
    "Se não souberem fazer, venham ter comigo que eu ilumino-vos, nem que para isso tenha que trazer um lanterna.",
    "Aquela treta da onda e da partícula, um tipo ainda vai ver o que é. Aquilo é como a história da Flatland. Os tipos da Flatland viviam e viam em 2D, por isso só viam partes das coisas em 3D. Se fosse um cilindro, os tipos viam um círculo, ou uma elipse.",
    "Sou Físico, e agora? Agora está é bom para ir para a praia.",
    "Não comeces o mês de Abril com desconfianças.",
    "Fazer contas provoca disfunção erétil.",
    "Físico que é físico só percebe de molas.",
    "Físico que é físico faz sempre um boneco.",
    "física conceptual? Você... você é poeta.",
    "Porquê que está a escrever a azul? Nem todos aqui são azuis. Nem toda a gente é necessariamente de sangue real.",
    "Aqui vale tudo. Até arrancar olhos. Desde que...seja bem feito, evidentemente.",
    "Não há bom vinho do Porto sem bom barril. E não há boa vida sem vinho do Porto.",
    "e você a dar-lhe. Escreva direito. Ai jesus...ai...eu ainda vou acabar a trabalhar num ATL.",
    "Você tem de fazer bem o boneco. Se o boneco ficar mal, depois não vai compreender o exercício.",
    "Um bocadinho de carga... Cria um bocadinho de campo.",
    "Há três tipos de alunos...os que sabem matemática, os que não sabem matemática e os que querem ser felizes. Você claramente não é o terceiro.",
    "O homem pode ser velho, mas com um berbequim consegue fazer tudo.",
    "Eu sou uma boa mãe. Dou por igual a todos os filhos.",
    "A física é só contas, e quem disser o contrário vê demasiado discovery channel.",
    "Deixe-se de fantasias, que isto aqui não é a guerra das estrelas!",
    "Um bocadinho é um deltinha e um bocadão é um deltão.",
    "Primeiro faz o boneco, depois vem a física e só depois a matemática. Isso não é matemática. Isso são contas.",
    "A menina é que tem um professor de categoria. Isto nem em Cambridge nem no MIT.",
    "Como vê, vai ter que sentar-se no meu colo.",
    "A conta é grande? Não há problema, termina amanhã. Mas faz.",
    "Coice de mula que se preze, segue a distribuição de Poisson.",
    "Uma das vantagens de ser professor é poder dizer: e por simetria...",
    "O que é preciso é encontrar uma boa( )zona!",
    "Sim... porque para ir a fundo... também convém ter tamanho.",
    "Se você está com problemas de existência e unicidade não está no sítio certo! Isso é no outro departamento! (aponta para o Departamento de matemática).",
    "Mas vocês não precisam de saber o nome disto...a não ser que queiram mostrar que sabem... o que... é diferente de saber.",
    "O nosso estudo fica-se por aqui...e já vai dar muita reprovação.",
    "Não basta a gente andar à chuva e molhar-se... há que a sentir... Bob Marley.",
    "Portanto... estou eu aqui todo porreiro da Silva a apanhar Sol...",
    "Qualquer criança de 4 meses compreende isto.",
    "Hão-de reparar que estas portas fecham-se sozinhas. Ora... não há corrente de ar... e a inteligência dos alunos também não está em expansão.",
    "Aprender é uma coisa, ensinar é outra. Há 2 lados da corda. Se os dois lados não puxam... a corda não estica.",
    "Isso é um estimulante. Espero que não tenha sido por causa do varão.",
    "Sempre me quis parecer que as meninas de física são caladinhas... mas lá fora são terríveis.",
    "Há um jogo de sedução entre o professor e o aluno. O professor resolve os exercícios de uma maneira sofisticada, para mostrar que sabe muito, e o aluno observa, absorve a gloriosidade e pensa \"quero ser como o meu Pai\".",
    "Este trabalho é herdeiro do pedantismo intelectual característico de artigos científicos.",
    "Vamos criar um operador à la mecânica quântica, Ô, com o chapéu. Hein? Já estão a aprender umas coisas...",
    "Normalmente não se faz a coisa assim. Podíamos dizer que no infinito a dependência vai ter de ser 1/r, cortar todos estes termos e chegar logo a solução - resolver a coisa à la Landau, um físico Russo...",
    "A terra é gorda na cintura... como acontece a muita boa gente e nao basta dzer que as gorduras vao todas para o brasil.",
    "Aqui estamos a resolver a coisa de maneira que qualquer burro faz isto (quer dizer, coitados dos burros, que até são inteligentes), mas tem de ser. Têm de aprender assim primeiro para mais tarde poderem fazer como o Landau.",
    "Está sorridente...? Estou a ver que está a gostar da performance.",
    "Você deve gostar muito de mim para me tentar impressionar dessa forma...",
    "A sua mãe não sou. Seu pai também não. Quer dizer... acho eu. Vai ter Mecânica Analítica no próximo semestre?",
    "Este trabalho é herdeiro do pedantismo intelectual característico de artigos científicos.",
    "Isto tem de ser servido homeopaticamente, às colherzinhas.",
    "Isso aí é jardinagem.",
    "Pode parecer elementar, mas no final vou ter de pagar as vacas ao dono na mesma. Não há almoços grátis!",
    "Mas cuidado... se fizermos isto, as equações de Euler vão ter um traumatismo craniano.",
    "Vou arrancar a porta, levá-la para casa e vendê-la...vale uns cobres. Até porque hoje em dia isto está... não é...",
    "Enquanto o aluno for tratado como o cliente que tem sempre razão... não funciona. Isto aqui NÃO é um serviço. E mesmo que fosse... o serviço paga-se... sim...",
    "Não se paga à entrada... paga-se à saída! Sim... tal como nas discotecas...não é...",
    "Vamos resolver isto em grupo. Mas é em grupo mesmo, não é em grupos do Facebook.",
    "Este integral não está definido, mas eles não nos pedem para primitivar, pedem-nos para integrar, o que significa que isto aqui é um número. E é aí que entra o Python. Sim... é para isso que o Python foi feito.",
    "Desde quando é que o campo magnético trabalha? O campo magnético é como eu, não faz nenhum!",
    "Você é um sonhador. Você sonha demasiado alto. Mas como bem sabe... quanto mais alto... maior é a queda. Não quer mudar de curso?",
    "O cliente tem de ser bem servido, se não queixa-se.",
    "Vocês perderam uma boa oportunidade de aprender isto. É no que estas aulas se traduzem - na perda de boas oportunidades para aprender. Mas pronto, um gajo tem de sobreviver.",
    "Vamos lá, não tenha medo. Eu estou aqui.",
    "Então tiveram Comunicação em Ciência... e não comunicam?!",
    "Não concordo consigo. Não... isso é a maneira burra de resolver o exercício. Isso aí é para formar eletricistas. Físicos... não.",
    "Pois... os brasileiros gostam muito de seduzir. Nós... nem tanto.",
    "Isto da selecção natural... É assim mais fuzzy, não é assim tão crispy, tem de haver margem para a biodiversidade.",
    "As bananas da Madeira são pequenas, mas são as mais saborosas.",
    "Você só apaga à direita? Não me diga que é de esquerda... não sei se a comissão parlamentar permite essas apagadelas tendenciosas.",
    "Isso não é assim que se diz. Isso é abrasileirado. Hmpf... os brasileiros... a criarem um dialecto que só eles conseguem perceber.",
    "Você não é só um engenheiro! Você é um engenheiro da física! O melhor engenheiro!",
    "Com que então prometeram-me sereias... E É ISTO QUE ME VEM PARAR À REDE...\r",
    "Vocês lembram-se do problema da aula anterior? Não se lembram?... eu tenho assim tantos dons encantatórios... que adormeço qualquer um...",
    "O exterior é um reservatório infinito... não aquece nem arrefece. Quando vão tomar um banho ao mar, ele não muda de temperatura. Pode mudar de cor, mas ISSO É OUTRO FENÓMENO...",
    "O teorema de Carnot é como o remédio de flor... cura tudo, seja onde for.",
    "Vamos passar ao problema 8... nem vale a pena perguntar se querem vir ao quadro ou não...",
    "E isto é um raciocínio linear... se não percebeu, ou não estudou... OU NÃO ESTÁ AQUI A FAZER NADA... não há terceira hipótese.",
    "A física é que é o difícil... a matemática são só uns bocadinhos... há que fazer render o peixe. *começa a cantar o hino nacional*",
    "Teorema de Stokes... teorema de Gauss... é tudo a mesma mer-coisa.",
    "Eu agora estou a trabalhar para os inquéritos pedagógicos...",
    "Isto é quase teoria das cordas...sabe calcular, mas não sabe o que é... é aquela velha máxima: quem não tem cão, caça com gato.",
    "Uma conta é um algoritmo, não é um raciocínio... e esta, hein? Uma conta até o Google faz.",
    "No ano passado tive um aluno que era poeta... a falar-me de física conceptual e fantasias assim...",
    "A resistência no início estava muda... no final saiu calada...",
    "Mas isso não interessa, isso são números... você olha para uma árvore e vê números? Números são uma coisa que não existe, só na nossa cabeça... tudo uma cambada de esquizofrénicos.",
    "Isto é como na engenharia... primeiro faça a coisa à ferreiro... depois faça a coisa à meio ferreiro.",
    "Não é para dar banho ao cão, mas é para dar banho ao chumbo.",
    "Os francess são latinos disfarçados.",
    "Deus não é brasileiro... eu gosto muito de picanha mas Deus não é brasileiro.",
    "Fórmulas? Quais fórmulas? Isto está para aqui uma central de comunicações desgraçada.",
    "É bastante improvável ir num avião com uma bomba. É por isso que eu levo sempre uma bomba comigo, porque ir num avião com duas bombas é ainda mais improvável.",
    "Isto não é fast mecânica analítica, é slow mecânica analítica.",
    "Bem meu caro, na vida nada é fácil, só no Facebook.",
    "Este curso anda a ficar Tiplerizado...",
    "Os engenheiros é que são os nabos... NÃO, ALIÁS, nós é que somos os inteligentes!",
    "A vida é assim, é sempre tau tau!",
    "Vocês estiveram parados nesta semana ou tiveram competências transcendentais?",
    "A ética e a moral é muito boa para os outros",
    "Em relatividade tudo complica",
    "Exímio utilizador da técnica do apagador",
    "A notação não é uma mariquice... A notação é tudo",
    "Os planos e as mulheres querem-se como a pescada... querem-se grandes",
    "Então vamos meter em cima, em cima há quem goste ainda mais",
    "O padrão sou eu é por isso que me pagam",
    "Nas árvores não está lá centímetros, decímetros e metros",
    "Mesmo quem não gosta pode por manteiga que é bom",
    "Você bem que usa a técnica do apagador ou não usa. Isso tem copyright",
    "Aqui é clássica! (diz, olhando para um gato que entrou no exame de Mecânica Analítica)",
    "A gente não pode ser como o Peter Pan, ser pequenino toda a vida.",
    "Antigamente, as pessoas eram ensinadas a serem neuróticas. Agora, são educadas a ser narcisistas.",
    "Isso é o quê? Um hieróglifo egipcio? Não sou propriamente um egitólogo. Isso já está fora do meu alcance.",
    "A homogeneidade está na moda. Agora, querem se convencer que não têm nada entre as pernas.",
    "Você é grande, mas aqui o tamanho não importa. Serve tudo para a mesma função.",
    "Eu aqui não deixo ninguém desamparado, sou como uma boa mãe. Ou como um bom pai, castigo!",
    "Vocês parecem velhinhos, todos na retranca. Deixem a juventude divertir-se. Vocês que idade têm? 75?",
    "Nós já não somos meninos, apesar de virmos de calcõeszinhos para as aulas. É para mostrar os pelos?Elas gostam disso? (olha para a única rapariga na sala) Ela não está a prestar atenção...",
    "Portanto, os primeiros dois exercícios são de mão beijada… Mas é preciso saber beijar… e isso treina-se em casa.",
    "Já dizia o nosso presidente: só dança quem está na roda. E ele é um homem que sabe",
    "Vocês controlem a hora disto porque eu não programei o meu bicharoco",
    "[massa por unidade de comprimento] mede o alentejano da corda, isto é, a inércia da corda",
    "Primeira lei da termodinâmica: tudo se paga neste mundo",
    "Pergunte ao seu colega. Ele é que é o mestre da culinária.(começa a assobiar a música)",
    "Quem aprendeu a conduzir um Fiat 500, não tem dificuldade em conduzir um Lamborghini. Mas que é diferente, é!",
    "Eu não tenho qualidade de puro. Puro, perfeito e omnipotente. Tenho as minhas limitações.",
]

const target = document.getElementById("quote")
const numQuotes = document.getElementById("num-quotes")
const numDesta = document.getElementById("num-desta")

let quoteEscolhida = Math.floor(Math.random() * quotes.length)

target.innerText = quotes[quoteEscolhida]
numQuotes.innerText = String(quotes.length)
numDesta.innerText = String(quoteEscolhida + 1)
